"""AI-drawn push creatives.

For each campaign the LLM describes a few distinct photo scenes for the
product *type* (never the Amazon listing photo, which may not be used in
ads, and never a brand logo), an image model draws them, and each drawing
is cut into the two files a push needs: the main image (492x328, same 3:2
shape as the 1536x1024 render) and a square icon cropped from its centre.

Anything failing here makes the caller fall back to the simple Pillow
creatives, so a broken image API never blocks a launch.
"""
from __future__ import annotations

import base64
import io
import logging
from pathlib import Path

from PIL import Image

from amzagent.config import Settings
from amzagent.content.llm import LLM, LLMError, parse_json
from amzagent.models import Product, ProductCopy
from amzagent.push.creatives import ICON_SIZE, IMAGE_SIZE

logger = logging.getLogger(__name__)

RENDER_SIZE = "1536x1024"  # 3:2, same shape as the 492x328 push image

SCENE_SYSTEM = (
    "You are an art director for mobile push-notification ads. You describe "
    "photographs to be generated by an image model. Reply with JSON only."
)

# Appended to every image prompt: what ad networks reject and what Amazon /
# trademark rules forbid.
IMAGE_RULES = (
    " Photorealistic advertising photo, natural light, bright and clean, "
    "single clear subject that reads well as a small thumbnail. Absolutely no "
    "text, letters, numbers, prices, logos, brand names, watermarks, badges, "
    "buttons, arrows or phone/OS interface elements."
)


class CreativeError(RuntimeError):
    pass


def describe_scenes(llm: LLM, product: Product, copy: ProductCopy, n: int) -> list[str]:
    prompt = (
        f"Product type: {copy.product_type or 'see title'}\n"
        f"Product title: {product.title}\n"
        f"Ad headline: {copy.push_title}\n\n"
        f"Describe {n} clearly different photo scenes (different setting, angle "
        "or person) that make someone want this kind of product. Show a "
        "generic, unbranded version of the product type in use or its result "
        "(e.g. for a juicer: a glass of fresh juice with fruit on a sunny "
        "kitchen counter). No brand names, no logos, no text in the image, no "
        "celebrities, no children's faces close-up, nothing medical or "
        "before/after. Return a JSON array of strings, one short paragraph each."
    )
    data = parse_json(llm.generate(SCENE_SYSTEM, prompt, max_tokens=800))
    scenes = [s for s in data if isinstance(s, str) and s.strip()] if isinstance(data, list) else []
    if not scenes:
        raise LLMError("No image scenes in model reply")
    return scenes[:n]


class OpenAIImages:
    def __init__(self, settings: Settings):
        if not settings.openai_api_key:
            raise CreativeError("OPENAI_API_KEY is not set")
        import openai

        self._client = openai.OpenAI(api_key=settings.openai_api_key)
        self._model = settings.openai_image_model
        self._quality = settings.openai_image_quality

    def draw(self, prompt: str) -> bytes:
        try:
            response = self._client.images.generate(
                model=self._model,
                prompt=prompt,
                size=RENDER_SIZE,
                quality=self._quality,
                n=1,
            )
        except Exception as exc:
            raise CreativeError(f"OpenAI image error: {exc}") from exc
        b64 = response.data[0].b64_json if response.data else None
        if not b64:
            raise CreativeError("OpenAI returned no image")
        return base64.b64decode(b64)


def cut_push_images(png: bytes, out_dir: Path, name: str) -> tuple[Path, Path]:
    """Save <name>-image.png (492x328) and <name>-icon.png (192x192, the
    centre square of the same picture)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    img = Image.open(io.BytesIO(png)).convert("RGB")
    w, h = img.size
    # Cover-crop to 3:2 in case the model returned another shape.
    target = IMAGE_SIZE[0] / IMAGE_SIZE[1]
    if w / h > target:
        new_w = int(h * target)
        img = img.crop(((w - new_w) // 2, 0, (w - new_w) // 2 + new_w, h))
    elif w / h < target:
        new_h = int(w / target)
        img = img.crop((0, (h - new_h) // 2, w, (h - new_h) // 2 + new_h))
    w, h = img.size
    image_path = out_dir / f"{name}-image.png"
    img.resize(IMAGE_SIZE, Image.LANCZOS).save(image_path, optimize=True)
    side = h
    icon = img.crop(((w - side) // 2, 0, (w - side) // 2 + side, side))
    icon_path = out_dir / f"{name}-icon.png"
    icon.resize(ICON_SIZE, Image.LANCZOS).save(icon_path, optimize=True)
    return icon_path, image_path


def make_ai_creatives(
    llm: LLM,
    painter,
    product: Product,
    copy: ProductCopy,
    out_dir: Path,
    name: str,
    variants: int,
) -> list[tuple[str, str]]:
    """Returns [(icon_filename, image_filename), ...], one per variant that
    rendered. Raises if none did."""
    scenes = describe_scenes(llm, product, copy, variants)
    made: list[tuple[str, str]] = []
    errors: list[str] = []
    for i, scene in enumerate(scenes, 1):
        try:
            png = painter.draw(scene + IMAGE_RULES)
            icon, image = cut_push_images(png, out_dir, f"{name}-v{i}")
        except (CreativeError, OSError, ValueError) as exc:
            errors.append(str(exc))
            continue
        made.append((icon.name, image.name))
    if not made:
        raise CreativeError("; ".join(errors) or "no variants rendered")
    return made
